services:
  app:
    image: dev-todo-front
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app 
    ports:
      - 3001:3000
    container_name: dev-todo-front
  # docker compose run debug-helper wget -O - http://app:3000
  debug-helper:
    image: busybox