services:
  app:
    image: dev-todo-front
    build:
      context: .
      dockerfile: dev.Dockerfile 
    volumes:
      - ./:/usr/src/app 
    ports:
      - 3001:3000
    container_name: dev-todo-front