version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_ROOT_DATABASE}
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
  redis: 
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --appendonly yes --loglevel warning
    volumes:
      - ./redis_data:/data
  
volumes:
  mongo_data:
  redis_data: